name: CI
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run jest unit tests
        run: yarn test
      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v2
