name: CI
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run jest unit tests
        run: yarn test
      - name: Build project
        run: yarn build
      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: "http://localhost:3000"
          browser: chrome
          headless: true
